### PR TITLE
Updated to add fix for issue 41 as discussed

### PR DESCRIPTION
**Pull request by accdc**
Pull req for issue 41 fix.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/accname/pull/44.html" title="Last updated on Aug 25, 2020, 8:08 PM UTC (8593b66)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/accname/44/7519efa...8593b66.html" title="Last updated on Aug 25, 2020, 8:08 PM UTC (8593b66)">Diff</a>

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/accname/pull/44.html" title="Last updated on Apr 20, 2022, 2:03 PM UTC (1eb4b00)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/accname/44/d8e6469...1eb4b00.html" title="Last updated on Apr 20, 2022, 2:03 PM UTC (1eb4b00)">Diff</a>

### CODE REVIEW

**Review by MelSumner — APPROVED** [review]
Looks like this needs a rebase but is otherwise okay.

**Comment by accdc** [comment]
Thanks, my git merging skills aren't as good as yours, :) can you help with the rebasing?

**Comment by MelSumner** [comment]
@accdc apologies for the delay; yes I will rebase so we can merge 👍

**Comment by MelSumner** [comment]
Closing this PR (sorry, I did something incorrectly in the rebase and it was too messy to revert)- re-did the changes in PR #156

**Pull request closed without merging**
